### ISSUE TITLE
A parsing error from wtf_wikipedia

### ISSUE THREAD

**Issue by imoonkey** [spencermountain/wikipedia-to-mongodb#1]
An error occurred when importing a certain page into mongodb, maybe this is a part of `wtf_wikipedia`'s problem.

I am not familiar to node.js, and it would be great if you can help with this. Thanks!

Command Line error:
```
Bayern
Bavaria
Brandenburg
Federal Chancellor
Bundestag
Bundesrat
Bundesregierung
BMW
Blaue Reiter
Bisexual (disambiguation)

[somewhere]/js-wikipedia-to-mongodb/node_modules/wtf_wikipedia/index.js:534
        if(!img.match(/^(image|file|fichier|Datei)/i)){
                ^
TypeError: Object 350 has no method 'match'
    at Object.main [as parse] ([somewhere]/js-wikipedia-to-mongodb/node_modules/wtf_wikipedia/index.js:534:17)
    at XmlStream.<anonymous> ([somewhere]/js-wikipedia-to-mongodb/index.js:28:26)
    at XmlStream.emit (events.js:106:17)
    at fn ([somewhere]/js-wikipedia-to-mongodb/node_modules/xml-stream/lib/xml-stream.js:132:14)
    at FiniteAutomata.run ([somewhere]/js-wikipedia-to-mongodb/node_modules/xml-stream/lib/finite-automata.js:32:19)
    at FiniteAutomata.leave ([somewhere]/js-wikipedia-to-mongodb/node_modules/xml-stream/lib/finite-automata.js:85:7)
    at null.<anonymous> ([somewhere]/js-wikipedia-to-mongodb/node_modules/xml-stream/lib/xml-stream.js:434:8)
    at emit (events.js:95:17)
    at Parser.parse ([somewhere]/js-wikipedia-to-mongodb/node_modules/xml-stream/node_modules/node-expat/lib/node-expat.js:23:22)
    at parseChunk ([somewhere]/js-wikipedia-to-mongodb/node_modules/xml-stream/lib/xml-stream.js:513:14)
```

**Comment by spencermountain** [comment]
hey, thanks. I've added a bugfix to wtf_wikipedia. hopefully that fixes it. Let me know if you can get through the whole wikipedia file. I ran out of hard drive space!
cheers
-spencer

**Comment by spencermountain** [comment]
(`npm install` should update the library)

**Comment by imoonkey** [comment]
Hi. I just commented that part as I do not care much about the images. With that, I got it running smoothly. Thanks for the fix. But it seems like I will need to reimport everything if I update the library and rerun. I will get my hands on it when I have time or need the image part.
