### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by kharazi** [spencermountain/wikipedia-to-mongodb#10]
I have this issue while running the script for fa wikipedia dump

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot read property '0' of undefined
    at f (/usr/lib/node_modules/wikipedia-to-mongodb/node_modules/unbzip2-stream/lib/bit_iterator.js:24:34)
    at Object.bzip2.decompress (/usr/lib/node_modules/wikipedia-to-mongodb/node_modules/unbzip2-stream/lib/bzip2.js:272:13)
    at decompressBlock (/usr/lib/node_modules/wikipedia-to-mongodb/node_modules/unbzip2-stream/index.js:29:28)
    at decompressAndQueue (/usr/lib/node_modules/wikipedia-to-mongodb/node_modules/unbzip2-stream/index.js:46:20)
    at Stream.end (/usr/lib/node_modules/wikipedia-to-mongodb/node_modules/unbzip2-stream/index.js:82:23)
    at _end (/usr/lib/node_modules/wikipedia-to-mongodb/node_modules/through/index.js:65:9)
    at Stream.stream.end (/usr/lib/node_modules/wikipedia-to-mongodb/node_modules/through/index.js:74:5)
    at ReadStream.onend (_stream_readable.js:485:10)
    at ReadStream.g (events.js:180:16)
    at ReadStream.emit (events.js:117:20)

```

**Comment by spencermountain** [comment]
hi Vahid, thanks for this. I'm not sure I can do much, as the stack trace doesn't go into any of wtf_wikipedia's codebase. There has been a couple bugfixes that haven't been released, wanna try it now (v0.6.0)? and maybe log which article throws that error somehow?
I know it's labourious. 
cheers
