### ISSUE TITLE
wp2mongo fails with an error

### ISSUE THREAD

**Issue by sbodenstein** [spencermountain/wikipedia-to-mongodb#30]
I have installed `wikipedia-to-mongodb` on a Ubuntu 16.04 EC2 machine (with Node.js version v4.2.6), and I get the following when trying to run the command:
```
ubuntu@ip-172-31-15-234:~$ wp2mongo afwiki-latest-pages-articles.xml.bz2
/usr/local/lib/node_modules/wikipedia-to-mongodb/bin/wp2mongo.js:2
let program = require('commander')
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```
Any ideas as to why this is failing would be greatly appreciated!

**Comment by sbodenstein** [comment]
This seems to be due to an ancient node.js. Closing.
